spring:
  datasource:
    url: jdbc:mysql://localhost:3306/one?useSSL=true
    username: root
    password: abc123_
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource


mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.jc.one.component
  global-config:
    db-config:
      id-type: id_worker
      field-strategy: not_empty
